services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3000:3000"
  inference:
    build:
      context: .
      dockerfile: inference.Dockerfile
      args:
        TORCH_WEIGHT_PATH: models/2023-11-09_16-35.pt
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: true
