services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3000:3000"
  inference:
    build:
      context: .
      dockerfile: inference.Dockerfile
    volumes:
      - type: bind
        source: models/
        target: /app/models/
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: true
      TORCH_WEIGHT_PATH: /app/models/gg-2023-11-10_10-20.pt
